---
name: YOLOL
on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Validate YOLOL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17.3"
      - name: Setup yodk
        run: go install github.com/dbaumgarten/yodk@latest
      - name: Validate
        run: |
          yodk verify ./**/**/*.yolol
          yodk verify ./**/**/**/*.yolol
          yodk verify ./**/**/**/**/*.yolol
